name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: taskmanager-apk
        path: bin/*.apk
